<?php
/* This file is autogenerated by setup.php. Do not edit directly. */
/* Generated by PhD $Id$ at Thu, 09 Aug 2007 15:10:10 +0200. */

$OPTIONS = array (
  'output_format' => array('xhtml'),
  'output_theme' => array(
    'xhtml' => array(
      'php' => array(
        'phpweb',
        'chunkedhtml',
        'bightml',
      ),
    ),
  ),
  'index' => true,
  'xml_root' => '/home/bjori/php/doc',
  'language' => 'en',
  'fallback_language' => 'en',
  'enforce_revisions' => false,
  'compatibility_mode' => true,
  'build_log_file' => 'none',
  'debug' => true,
);

die("You need to edit xml_root in config.php");

