<?php
function v($msg) {
	$args = func_get_args();
	$args[0] = date($GLOBALS["OPTIONS"]["date_format"]);
	vfprintf(STDERR, "[%s] $msg", $args);
}

define('VERBOSE_INDEXING',               0x01);
define('VERBOSE_FORMAT_RENDERING',       0x02);
define('VERBOSE_THEME_RENDERING',        0x04);
define('VERBOSE_RENDER_STYLE',           0x08);
define('VERBOSE_PARTIAL_READING',        0x10);
define('VERBOSE_PARTIAL_CHILD_READING',  0x20);
define('VERBOSE_TOC_WRITING',            0x40);
define('VERBOSE_CHUNK_WRITING',          0x80);

define('VERBOSE_ALL',VERBOSE_INDEXING|VERBOSE_FORMAT_RENDERING|VERBOSE_THEME_RENDERING|VERBOSE_RENDER_STYLE|VERBOSE_PARTIAL_READING|VERBOSE_PARTIAL_CHILD_READING|VERBOSE_TOC_WRITING|VERBOSE_CHUNK_WRITING);

/* Generated by PhD $Id$ at Thu, 09 Aug 2007 15:10:10 +0200. */

$OPTIONS = array (
  'output_format' => array('xhtml'),
  'output_theme' => array(
    'xhtml' => array(
      'php' => array(
        'phpweb',
        'chunkedhtml',
        'bightml',
      ),
    ),
  ),
  'index' => true,
  'xml_root' => '.',
  'language' => 'en',
  'fallback_language' => 'en',
  'enforce_revisions' => false,
  'compatibility_mode' => true,
  'build_log_file' => 'none',
  'debug' => true,
  'verbose' => VERBOSE_INDEXING|VERBOSE_FORMAT_RENDERING|VERBOSE_THEME_RENDERING|VERBOSE_RENDER_STYLE|VERBOSE_PARTIAL_READING|VERBOSE_TOC_WRITING,
  'date_format' => "H:i:s",
  'render_ids' => array(
	/*
	"manual"           => false,
	"ref.strings"      => false,
	"function.strpos"  => true,
	"function.sprintf" => true,
	"ref.filesystem"   => true,
	*/
  ),
);
$OPTIONS["chunk_extra"]["legalnotice"] = true;


if ($argc == 2) {
    $OPTIONS["xml_root"] = $argv[1];
}

while (!is_dir($OPTIONS["xml_root"]) || !is_file($OPTIONS["xml_root"] . "/.manual.xml")) {
    print "I need to know where you keep your '.manual.xml' file (I didn't find it in " . $OPTIONS["xml_root"] . "): ";
    $root = trim(fgets(STDIN));
    if (is_file($root)) {
        $OPTIONS["xml_root"] = dirname($root);
    } else {
        $OPTIONS["xml_root"] = $root;
    }
}

$OPTIONS["xml_file"] = $OPTIONS["xml_root"] . "/.manual.xml";
$OPTIONS["version_info"] = $OPTIONS["xml_root"]."/phpbook/phpbook-xsl/version.xml";
$OPTIONS["acronyms_file"] = $OPTIONS["xml_root"]."/entities/acronyms.xml";

